[package]
name = "sql_formatter"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "sql_formatter"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
sqlformat = "0.2.6"
